[providers]
node = true
deno = false

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh", "chmod +x start.sh"]

[phases.start]
cmd = "./start.sh"
nixpacksPath = false

[variables]
NODE_ENV = "development"
NIXPACKS_NO_DENO = "1"
NIXPACKS_PROVIDER = "node"